linters-settings:
  govet:
    enable-all: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/eslutz/Messagarr
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - goconst
        - lll
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
